title: Electronic Notebook Lab

### Theme
# theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs

### Color scheme supports "light" (default) and "dark"
color_scheme: light

aux_links:
  "Project Template on GitHub":
    - "//github.com/luquelab/project_template"



# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:		
# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
  heading_level: 2